# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/egpt',
                'doc_host': 'https://tuuai.github.io',
                'git_url': 'https://github.com/tuuai/egpt',
                'lib_path': 'egpt'},
  'syms': {'egpt.core': {'egpt.core.foo': ('core.html#foo', 'egpt/core.py')}}}
